# Simplified Render Deployment Configuration
databases:
  - name: inferencemd-db
    plan: free
    postgresMajorVersion: 14

services:
  # Backend Web Service (FastAPI)
  - type: web
    name: inferencemd-backend
    runtime: docker
    plan: standard
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    envVars:
      # Essential variables only
      - key: DATABASE_URL
        fromDatabase:
          name: inferencemd-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER_FRONTEND_URL
        value: https://inferencemd-frontend.onrender.com
      - key: GOOGLE_API_KEY
        sync: false

  # Frontend Static Site (React)
  - type: web
    name: inferencemd-frontend
    runtime: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: ./frontend/build
    envVars:
      # Correct environment variable name expected by ApiService.ts
      - key: REACT_APP_API_URL 
        # Construct the full URL including the /api path prefix
        # Assuming 'url' property provides the full base URL (e.g., https://service.onrender.com)
        # We append '/api' to it. Adjust if Render uses a different property name.
        value: ${inferencemd-backend.url}/api
