version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app/app  # For development
      - ./reports:/app/reports
      - ./static:/app/static
    environment:
      - DATABASE_URL=sqlite:///./medhastra.db
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_BASE=${AZURE_OPENAI_API_BASE}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2023-05-15}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - REPORTS_DIR=/app/reports
      - STATIC_DIR=/app/static
    restart: unless-stopped
